// <auto-generated />
using System;
using ApiDeEscola.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiDeEscola.Migrations
{
    [DbContext(typeof(DataApplicationContext))]
    [Migration("20250412051625_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiDeEscola.Models.EmploymentModel", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("VARCHAR(11)");

                    b.Property<DateTime>("Date_Employment")
                        .HasColumnType("DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Salary")
                        .HasColumnType("FLOAT");

                    b.Property<int>("idade")
                        .HasMaxLength(110)
                        .HasColumnType("int");

                    b.HasKey("CPF")
                        .HasName("PK_CPF");

                    b.ToTable("Employments");
                });

            modelBuilder.Entity("ApiDeEscola.Models.UsersModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(45)");

                    b.Property<string>("Emaíl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
